quarkus:
  application:
    name: notification-service
    version: 1.0.0

  http:
    port: 8083
    host: 0.0.0.0

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/notifications_db
    reactive:
      url: postgresql://localhost:5432/notifications_db

  hibernate-orm:
    database:
      generation: none

  flyway:
    migrate-at-start: true
    locations: classpath:db/migration

  redis:
    host: localhost
    port: 6379

  kafka:
    health:
      enabled: true

  mp:
    messaging:
      incoming:
        payment-events-in:
          connector: smallrye-kafka
          topic: payment.events
          value.deserializer: io.quarkus.kafka.client.serialization.JsonDeserializer
          group: notification-service
          auto:
            offset: earliest

  oidc:
    auth-server-url: http://localhost:8180/realms/wallet
    client-id: wallet-backend
    enabled: true
    credentials:
      secret: secret

  opentelemetry:
    enabled: true
    service:
      name: notification-service

  smallrye-health:
    enabled: true
    expose:
      enabled: true

  log:
    console:
      enable: true
    level: INFO
    category:
      "com.wallet.notification": INFO
