quarkus:
  datasource:
    username: wallet
    password: change-me
    jdbc:
      url: jdbc:postgresql://postgres:5432/notifications_db
    reactive:
      url: postgresql://postgres:5432/notifications_db

  redis:
    hosts: redis://redis:6379

  kafka:
    bootstrap-servers: kafka:9092

  oidc:
    auth-server-url: http://keycloak:8180/realms/wallet

  opentelemetry:
    exporter:
      otlp:
        endpoint: http://otel-collector:4317

mp:
  messaging:
    connector:
      smallrye-kafka:
        bootstrap:
          servers: kafka:9092
    incoming:
      payment-events-in:
        connector: smallrye-kafka
        topic: payment.events
        value.deserializer: io.quarkus.kafka.client.serialization.JsonDeserializer
        group: notification-service
        auto.offset.reset: earliest
