quarkus:
  application:
    name: notification-service
    version: 1.0.0

  http:
    port: 8083
    host: 0.0.0.0

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/notifications_db
    reactive:
      url: postgresql://localhost:5432/notifications_db

  hibernate-orm:
    database:
      generation: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  flyway:
    migrate-at-start: true
    validate-on-migrate: false
    table: flyway_schema_history_notification
    locations: classpath:db/migration

  redis:
    hosts: redis://localhost:6379

  kafka:
    bootstrap-servers: localhost:9092
    health:
      enabled: true

  oidc:
    auth-server-url: http://localhost:8180/realms/wallet
    client-id: wallet-backend
    enabled: true
    credentials:
      secret: "p4PPO2LQkZfJfMOeQ4xYoXs541tpxmzC"

  smallrye-health:
    enabled: true
    expose:
      enabled: true

  log:
    console:
      enable: true
    level: INFO
    category:
      "com.wallet.notification": INFO

mp:
  messaging:
    connector:
      smallrye-kafka:
        bootstrap:
          servers: localhost:9092
    incoming:
      payment-events-in:
        connector: smallrye-kafka
        topic: payment.events
        value.deserializer: io.quarkus.kafka.client.serialization.JsonDeserializer
        group: notification-service
        auto.offset.reset: earliest
