quarkus:
  application:
    name: payment-service
    version: 1.0.0

  http:
    port: 8081
    host: 0.0.0.0

  grpc:
    port: 9081
    host: 0.0.0.0

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/payments_db
    reactive:
      url: postgresql://localhost:5432/payments_db

  hibernate-orm:
    database:
      generation: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    validate-in-dev-mode: true

  hibernate-reactive:
    default-schema: public

  flyway:
    migrate-at-start: true
    validate-on-migrate: false
    table: flyway_schema_history_payment
    schemas: public
    locations: classpath:db/migration

  redis:
    hosts: redis://localhost:6379

  kafka:
    bootstrap-servers: localhost:9092
    health:
      enabled: true

  mp:
    messaging:
      connector:
        smallrye-kafka:
          bootstrap:
            servers: localhost:9092
      outgoing:
        payment-events-out:
          connector: smallrye-kafka
          topic: payment.events
          value.serializer: io.quarkus.kafka.client.serialization.JsonbSerializer
          acks: all
          key.serializer: io.quarkus.kafka.client.serialization.StringSerializer
          auto:
            create: true

  oidc:
    auth-server-url: http://localhost:8180/realms/wallet
    client-id: wallet-backend
    enabled: true
    application-type: service
    credentials:
      secret: "9Jto5rgsmk2JUCbgg1W4hoBJe60soDCU"

  smallrye-fault-tolerance:
    enabled: true

  micrometer:
    export:
      prometheus:
        enabled: true

  smallrye-health:
    enabled: true
    expose:
      enabled: true
      path: /q/health
    ui:
      enabled: true
      path: /q/health/ui

  smallrye-openapi:
    info:
      title: Payment Service API
      description: Payment processing service for the Digital Wallet platform
      version: "1.0.0"
    path: /q/openapi

  log:
    console:
      enable: true
      format: "%d{yyyy-MM-dd HH:mm:ss} [%p] [%t{...}] %s%e%n"
    level: INFO
    category:
      "com.wallet.payment": INFO
      "io.quarkus": INFO

wallet:
  idempotency:
    ttl-hours: 24
