quarkus:
  # ========================================
  # Docker overrides
  # ========================================
  datasource:
    jdbc:
      url: jdbc:postgresql://postgres:5432/payments_db
    reactive:
      url: postgresql://postgres:5432/payments_db

  redis:
    host: redis

  kafka:
    health:
      enabled: true

  mp:
    messaging:
      outgoing:
        payment-events-out:
          connector: smallrye-kafka
          topic: payment.events
          value.serializer: io.quarkus.kafka.client.serialization.JsonbSerializer
          acks: all
          key.serializer: io.quarkus.kafka.client.serialization.StringSerializer

  oidc:
    auth-server-url: http://keycloak:8180/realms/wallet

  opentelemetry:
    exporter:
      otlp:
        endpoint: http://otel-collector:4317
