quarkus:
  datasource:
    username: wallet
    password: change-me
    jdbc:
      url: jdbc:postgresql://postgres:5432/payments_db
      telemetry: true
    reactive:
      url: postgresql://postgres:5432/payments_db

  redis:
    hosts: redis://redis:6379

  kafka:
    bootstrap-servers: kafka:9092

  mp:
    messaging:
      connector:
        smallrye-kafka:
          bootstrap:
            servers: kafka:9092

  oidc:
    auth-server-url: http://keycloak:8180/realms/wallet
    token:
      issuer: http://localhost:8180/realms/wallet

  otel:
    enabled: true
    exporter:
      otlp:
        protocol: grpc
        endpoint: http://otel-collector:4317

wallet:
  idempotency:
    ttl-hours: 24
