quarkus:
  datasource:
    username: wallet
    password: change-me
    jdbc:
      url: jdbc:postgresql://postgres:5432/wallet
    reactive:
      url: postgresql://postgres:5432/wallet

  redis:
    hosts: redis://redis:6379

  kafka:
    bootstrap-servers: kafka:9092

  mp:
    messaging:
      connector:
        smallrye-kafka:
          bootstrap:
            servers: kafka:9092

  oidc:
    auth-server-url: http://keycloak:8180/realms/wallet
    token:
      issuer: http://localhost:8180/realms/wallet
