quarkus:
  oidc:
    auth-server-url: http://keycloak:8180/realms/wallet
    token:
      issuer: http://keycloak:8180/realms/wallet

  opentelemetry:
    exporter:
      otlp:
        endpoint: http://otel-collector:4317

keycloak:
  admin:
    url: http://keycloak:8180
