quarkus:
  oidc:
    auth-server-url: http://keycloak:8180/realms/wallet
    client-id: wallet-backend
    credentials:
      secret: "p4PPO2LQkZfJfMOeQ4xYoXs541tpxmzC"

  otel:
    enabled: true
    exporter:
      otlp:
        protocol: grpc
        endpoint: http://otel-collector:4317

keycloak:
  admin:
    url: http://keycloak:8180
